on:
  workflow_call:
    inputs:
      is_tag:
        description: 'Is a Git Tag'
        type: string
        required: true
      current_branch_tag:
        description: 'Git branch or Tag'
        type: string
        required: true
      runner:
        description: 'Runner'
        type: string
        required: true
      runner_type:
        description: 'Runner type'
        type: string
        required: true
      platform:
        description: 'platform'
        type: string
        required: true
      stable_unstable:
        description: 'stable_unstable type'
        type: string
        required: true
      tests_group:
        description: 'tests group pg, others, full'
        type: string
        required: true
      image_type:
        description: 'image type: full, normal'
        type: string
        required: true

jobs:
  run-integ-tests:
    runs-on: ${{ inputs.runner }}
    steps:
    - name: Install Integration tests prerequisites
      run: sudo apt-get install -y dcmtk

    - name: Pull image
      run: docker pull orthancteam/orthanc-pre-release:${{ inputs.current_branch_tag }}-${{ inputs.image_type }}-${{ inputs.stable_unstable }}-for-tests

    - name: Run normal image integration tests
      # TODO: enable on ARM64 too
      if: inputs.runner_type == 'github-hosted'
      run: ./run-integration-tests.sh version=${{ inputs.stable_unstable }} image=${{ inputs.image_type }} imageUnderTest=orthancteam/orthanc-pre-release:${{ inputs.current_branch_tag }}-${{ inputs.image_type }}-${{ inputs.stable_unstable }}-for-tests testsGroup=${{ inputs.tests_group }}
      working-directory: ${{github.workspace}}/docker/integration-tests
